[versions]
configurate4 = "4.1.2"
adventure4 = "4.14.0"
cluster5 = "6.0"

[plugins]
hangar = { id = "io.papermc.hangar-publish-plugin", version = "0.1.0" }
modrinth = { id = "com.modrinth.minotaur", version = "2.8.4" }

paperweight = { id = "io.papermc.paperweight.userdev", version = "1.5.9" }
runpaper = { id = "xyz.jpenilla.run-paper", version = "2.2.2" }
shadowjar = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }

[libraries]
adventure4 = { module = "net.kyori:adventure-api", version.ref = "adventure4" }
minimessage4 = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure4" }

cluster5 = { module = "com.ryderbelserion.cluster:paper", version.ref = "cluster5" }
clusterApi5 = { module = "com.ryderbelserion.cluster:api", version.ref = "cluster5" }

configurate4-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate4" }

hikari = { module = "com.zaxxer:HikariCP", version = "5.1.0" }

vault = { module = "com.github.MilkBowl:VaultAPI", version = "1.7.1" }

configme = { module = "ch.jalu:configme", version = "1.4.1" }

bstats = { module = "org.bstats:bstats-bukkit", version = "3.0.2" }

commandApi = { module = "dev.jorel:commandapi-bukkit-shade", version = "9.3.0" }
commandAnnotations = { module = "dev.jorel:commandapi-annotations", version = "9.3.0" }

[bundles]
adventure = ["adventure4", "minimessage4"]

configurate4 = ["configurate4-yaml"]